docs: Update README (#17)
* fix build errors

* fix: s/little/Little on endian enum

* ci: add zig version check

* Revert "fix: s/little/Little on endian enum"

This reverts commit 119acb03f79ab821297729ce3c4acee757cc8a98.

* add setError

* readme until json

* feat: add getVarInt and setVarInt to be consistent with go pdk

* feat: allow allocation and finding memory block from Plugin

* docs: Add the rest of the README

* Apply suggestions from code review

Co-authored-by: Doğu Us <73913444+usdogu@users.noreply.github.com>

* fix Host function example

* change basic example target name

* add examples from readme to basic.zig

* fix tests

* fix tests

* add more tests

* only run CI for main

* fix tests

* fix tests

* fix tests

---------

Co-authored-by: Steve Manuel <steve@dylib.so>
Co-authored-by: Doğu Us <73913444+usdogu@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,9 @@
 name: CI
-on: [push, pull_request]
+on:
+  push:
+    branches: [ main ]
+  pull_request:
+    branches: [ main ]
 
 jobs:
   test-example:
@@ -14,6 +18,9 @@ jobs:
 
       - name: Install Zig
         uses: goto-bus-stop/setup-zig@v2
+
+      - name: Check Zig Version
+        run: zig version
           
       - name: Compile example
         run: |
@@ -21,11 +28,33 @@ jobs:
 
       - name: Test example
         run : |
-          TEST=$(extism call zig-out/bin/Basic\ example.wasm --input "this is a test" --set-config='{"thing": "1", "a": "b"}' --log-level=debug count_vowels | jq)
+          TEST=$(extism call zig-out/bin/basic-example.wasm --input "this is a test" --set-config='{"thing": "1", "a": "b"}' --log-level=debug count_vowels | jq)
           echo $TEST | grep '"count": 4'
           echo $TEST | grep '"config": "1"'
           echo $TEST | grep '"a": "this is var a"'
 
-          TEST=$(extism call zig-out/bin/Basic\ example.wasm make_http_request --allow-host '*')
+          TEST=$(extism call zig-out/bin/basic-example.wasm http_get --allow-host '*')
           echo $TEST
           echo $TEST | grep '"userId": 1'
+
+          TEST=$(extism call zig-out/bin/basic-example.wasm greet --config user=Benjamin)
+          echo $TEST
+          echo $TEST | grep 'Hello, Benjamin!'
+
+          TEST=$(extism call zig-out/bin/basic-example.wasm greet 2>&1 || true)
+          echo $TEST
+          echo $TEST | grep "Error: This plug-in requires a 'user' key in the config"
+
+          TEST=$(extism call zig-out/bin/basic-example.wasm add --input='{"a": 20, "b": 21}')
+          echo $TEST | grep '{"sum":41}'
+
+          TEST=$(extism call zig-out/bin/basic-example.wasm count --loop '3')
+          echo $TEST | grep '1'
+          echo $TEST | grep '2'
+          echo $TEST | grep '3'
+
+          TEST=$(extism call zig-out/bin/basic-example.wasm log_stuff --log-level 'debug' 2>&1)
+          echo $TEST | grep 'An info log!'
+          echo $TEST | grep 'A debug log!'
+          echo $TEST | grep 'A warning log!'
+          echo $TEST | grep 'An error log!'
